---
# handlers file for failover
- name: save iptables
  ansible.builtin.command:
    cmd: service iptables save
  become: yes

- name: restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted
  become: yes
